spring.datasource.url=jdbc:mysql://localhost:3306/resolver
spring.datasource.username=root
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mysecretkeymysecretkeymysecretkey
logging.level.root=INFO
logging.level.com.resolver=DEBUG
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
info.app.name=Resolver
info.app.description=Customer issue resolution backend
info.app.version=1.0